# Generated by Django 5.2.6 on 2025-10-26 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_foodlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('waist', models.FloatField(help_text='Waist circumference in cm')),
                ('hips', models.FloatField(help_text='Hips circumference in cm')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('user_profile', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('user_profile', 'date')},
            },
        ),
    ]
